version: '3.8'

services:
  postgres:
    container_name: "soa2"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data